create table if not exists users
(
    name  varchar(64),
    email varchar(64),
    id    bigint generated by default as identity
        primary key
);

create table if not exists items
(
    id      bigint generated by default as identity,
    user_id bigint
        constraint items_foreign_key
            references users (Id),
    url     varchar(256)
);

